//@ sourceMappingURL=CommandRunner.map
// Generated by CoffeeScript 1.6.0
(function() {
  var CommandRunner, Settings, commandRunnerPath, logger, _ref;

  Settings = require("settings-sharelatex");

  logger = require("logger-sharelatex");

  if (((_ref = Settings.clsi) != null ? _ref.dockerRunner : void 0) === true) {
    commandRunnerPath = "./DockerRunner";
  } else {
    commandRunnerPath = "./LocalCommandRunner";
  }

  logger.info({
    commandRunnerPath: commandRunnerPath
  }, "selecting command runner for clsi");

  CommandRunner = require(commandRunnerPath);

  module.exports = CommandRunner;

}).call(this);
