//@ sourceMappingURL=ContentTypeMapper.map
// Generated by CoffeeScript 1.6.0
(function() {
  var ContentTypeMapper, Path;

  Path = require('path');

  module.exports = ContentTypeMapper = {
    map: function(path) {
      switch (Path.extname(path)) {
        case '.txt':
        case '.html':
        case '.js':
        case '.css':
        case '.svg':
          return 'text/plain';
        case '.csv':
          return 'text/csv';
        case '.pdf':
          return 'application/pdf';
        case '.png':
          return 'image/png';
        case '.jpg':
        case '.jpeg':
          return 'image/jpeg';
        case '.tiff':
          return 'image/tiff';
        case '.gif':
          return 'image/gif';
        default:
          return 'application/octet-stream';
      }
    }
  };

}).call(this);
