//@ sourceMappingURL=DbQueue.map
// Generated by CoffeeScript 1.6.0
(function() {
  var Settings, async, logger, queue;

  async = require("async");

  Settings = require("settings-sharelatex");

  logger = require("logger-sharelatex");

  queue = async.queue(function(task, cb) {
    return task(cb);
  }, Settings.parallelSqlQueryLimit);

  queue.drain = function() {
    return logger.debug('all items have been processed');
  };

  module.exports = {
    queue: queue
  };

}).call(this);
