//@ sourceMappingURL=DraftModeManager.map
// Generated by CoffeeScript 1.6.0
(function() {
  var DraftModeManager, fs, logger;

  fs = require("fs");

  logger = require("logger-sharelatex");

  module.exports = DraftModeManager = {
    injectDraftMode: function(filename, callback) {
      if (callback == null) {
        callback = function(error) {};
      }
      return fs.readFile(filename, "utf8", function(error, content) {
        var modified_content;
        if (error != null) {
          return callback(error);
        }
        if ((content != null ? content.indexOf("\\documentclass\[draft") : void 0) >= 0) {
          return callback();
        }
        modified_content = DraftModeManager._injectDraftOption(content);
        logger.log({
          content: content.slice(0, 1024),
          modified_content: modified_content.slice(0, 1024),
          filename: filename
        }, "injected draft class");
        return fs.writeFile(filename, modified_content, callback);
      });
    },
    _injectDraftOption: function(content) {
      return content.replace(/\\documentclass\[/g, "\\documentclass[draft,").replace(/\\documentclass\{/g, "\\documentclass[draft]{");
    }
  };

}).call(this);
